# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f55b7a1f57fc61973141cedb3ffe9fb8d4142c1d54b4ad4b8544bbafef780b31067d2eb21553eed3ca155ac33a9114ba3b3b3bc0e89d2d75e5b123c358753f3a

test:
  secret_key_base: 0f94cee5cedb4c1a110c1f32cf4f2ee103ef8746c1655c241eea4900608c3acb77fcf994d821496f7d43e21431fc0fb581f5ed44f8ea569c9b4ec0315a5348fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
